export const fields = {
  employeeId: {
    type: 'employeeId',
    label: 'Employee ID',
    required: true,
  },
  fullName: {
    type: 'fullname',
    label: 'Full Name',
    required: true,
    trim: true,
  },
  email: {
    type: 'email',
    label: 'Email',
    required: true,
    trim: true,
  },
  password: {
    type: 'password',
    label: 'Password',
    disableForTable: true,
    disableForUpdate: true,
    disableForForm: false,
    required: true,
    disableForView: true,
  },
  phone: {
    type: 'phone',
    label: 'Phone',
    required: true,
  },
  gender: {
    type: 'select',
    label: 'Gender',
    required: true,
    placeholder: 'Select gender',
    options: [
      { label: 'Male', value: 'Male' },
      { label: 'Female', value: 'Female' },
      { label: 'Transgender', value: 'Transgender' },
      { label: 'Other', value: 'Other' },
    ],
  },
  dateOfBirth: {
    type: 'date',
    label: 'Date of Birth',
    required: true,
  },
  country: {
    type: 'country',
    required: true,
    label: 'Country',
  },
  address: {
    type: 'textarea',
    label: 'Address',
    required: true,
    trim: true,
  },
  department: {
    type: 'department',
    label: 'Department',
    required: true,
    trim: true,
  },
  designation: {
    type: 'designation',
    label: 'Designation',
    required: true,
    trim: true,
  },
  employeeType: {
    type: 'select',
    label: 'Employment Type',
    placeholder: 'Select employee type',
    required: true,
    options: [
      { label: 'Full-time', value: 'Full-time' },
      { label: 'Part-time', value: 'Part-time' },
      { label: 'Contract', value: 'Contract' },
      { label: 'Internship', value: 'Internship' },
    ],
  },
  bankName: {
    type: 'bankname',
    required: true,
    trim: true,
    label: 'Bank Name',
  },
  bankAccountNumber: {
    type: 'accno',
    required: true,
    label: 'Bank Account No.',
    trim: true,
  },
  bankIFSC: {
    type: 'ifsccode',
    required: true,
    label: 'IFSC Code',
    trim: true,
  },
  panNo: {
    type: 'panno',
    required: true,
    label: 'Pan No.',
    trim: true,
  },
  aadhaarNo: {
    type: 'aadhaar',
    required: true,
    label: 'Aadhaar No.',
    trim: true,
  },
  joiningDate: {
    type: 'date',
    label: 'Joining Date',
    required: true,
  },
  basicSalary: {
    type: 'number',
    label: 'Basic Salary',
    required: true,
  },
  status: {
    type: 'select',
    label: 'Status',
    placeholder: 'Select status',
    required: true,
    options: [
      { label: 'Active', value: 'Active' },
      { label: 'Inactive', value: 'Inactive' },
      { label: 'Terminated', value: 'Terminated' },
      { label: 'On Leave', value: 'On Leave' },
    ],
  },
  role: {
    type: 'select',
    label: 'Role',
    placeholder: 'Select role',
    required: true,
    options: [{ label: 'Employee', value: 'employee' }],
  },
};
